### ISSUE TITLE
cl : Command line error D8021 : invalid numeric argument '/Wno-shorten-64-to-32'

### ISSUE THREAD

**Issue by zhaoyueplc** [PartnershipOnAI/safelife#11]
I've installed vs2015, python 3.5.3, win10

I installed the project locally and ran: python setup.py build_ext --inplace, get the following error:

(venv) C:\safelife-master\safelife-master>python setup.py build_ext --inplace
running build_ext
building 'safelife.speedups' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPY_ARRAY_UNIQUE_SYMBOL=safelife_speed
ups -DNPY_NO_DEPRECATED_API=NPY_1_11_API_VERSION -IC:\safelife-master\safelife-master\safelife\speedups_src -IC:\safelife-master\safelife-master\venv\l
ib\site-packages\numpy\core\include -IC:\safelife-master\safelife-master\venv\include -ID:\python3.5.3\include -ID:\python3.5.3\include "-IC:\Program F
iles (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Wind
ows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /TcC:\saf
elife-master\safelife-master\safelife\speedups_src\advance_board.c /Fobuild\temp.win-amd64-3.5\Release\safelife-master\safelife-master\safelife\speedup
s_src\advance_board.obj -O3 -Wno-shorten-64-to-32 -Wno-c++11-extensions
**cl : Command line error D8021 : invalid numeric argument '/Wno-shorten-64-to-32'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2**

It should come from setup.py ：

extra_ compile_ args=[

'-O3',

'-Wno-shorten-64-to-32',

'-Wno-c++11-extensions',

]

**Comment by clwainwright** [comment]
I haven't actually tested compilation on a Windows machine, but the `extra_compile_args` are all optional and should be able to be removed if they're causing trouble. The `-O3` arg is an optimization flag and may make your code run faster, but the other two are just there to suppress compiler warnings. If you remove `extra_compile_args` from `setup.py`, does that allow you to compile successfully?

**Comment by zhaoyueplc** [comment]
extra_compile_args have been remove, then the following error pops up:
(venv) C:\safelife-master\safelife-master>python setup.py build_ext --inplace
running build_ext
building 'safelife.speedups' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPY_ARRAY_UNIQUE_SYMBOL=safelife_speed
ups -DNPY_NO_DEPRECATED_API=NPY_1_11_API_VERSION -IC:\safelife-master\safelife-master\safelife\speedups_src -IC:\safelife-master\safelife-master\venv\l
ib\site-packages\numpy\core\include -IC:\safelife-master\safelife-master\venv\include -ID:\python3.5.3\include -ID:\python3.5.3\include "-IC:\Program F
iles (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Wind
ows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /TcC:\saf
elife-master\safelife-master\safelife\speedups_src\advance_board.c /Fobuild\temp.win-amd64-3.5\Release\safelife-master\safelife-master\safelife\speedup
s_src\advance_board.obj
advance_board.c
C:\safelife-master\safelife-master\safelife\speedups_src\advance_board.c(38): error C2057: expected constant expression
C:\safelife-master\safelife-master\safelife\speedups_src\advance_board.c(38): error C2466: cannot allocate an array of constant size 0
C:\safelife-master\safelife-master\safelife\speedups_src\advance_board.c(38): error C2133: 'c1': unknown size
C:\safelife-master\safelife-master\safelife\speedups_src\advance_board.c(39): warning C4034: sizeof returns 0
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by clwainwright** [comment]
Hmm, I'll take a look at this tomorrow and see if I can get a Windows machine provisioned to get this sorted out. Thanks for the bug report.

**Comment by clwainwright** [comment]
@zhaoyueplc I think I fixed the issue. For some reason MSVS does not implement the C99 standard, so I needed to remove a few references to variable-length arrays. Would you mind taking a look at the above pull request and let me know if it fixes your problem?

**Comment by zhaoyueplc** [comment]
Hi ，
Thanks for your quick response .
Fixed. You may close this issue.
:)
