### ISSUE TITLE
Possible reproducibility bug

### ISSUE THREAD

**Issue by pde** [PartnershipOnAI/safelife#13]
I think I accidentally ran two copies of the same experiment, but got different results:

https://app.wandb.ai/safelife/asym1/runs/3u84ca3r/overview
https://app.wandb.ai/safelife/asym1/runs/29nsbg7t/overview

**Comment by clwainwright** [comment]
@pde Just pushed a fix to the multiagent branch. We weren't actually setting the seed for torch, just the level generator and other numpy functions, so it's not surprising that you'd get different results.
