### ISSUE TITLE
Do you have any plans to add multiple agents in the next step？

### ISSUE THREAD

**Issue by zhaoyueplc** [PartnershipOnAI/safelife#14]
To Whom It May Concern
Do you have any plans to add multiple agents in the next step?

**Comment by clwainwright** [comment]
See branch `multiagent` :)

A work in progress.

![scarce-resources](https://user-images.githubusercontent.com/6962678/90099517-867f3700-dcef-11ea-8029-8cdf87e3e174.gif)

**Comment by clwainwright** [comment]
This is now released to master!
